#!/usr/bin/env python3
"""Build aggregate catalog files from one JSON record per paper/resource."""
from pathlib import Path
import csv, json, re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = ROOT / "data" / "records"
OUT = ROOT / "data"

def sort_key(r):
    m = re.match(r"([A-Za-z]+)(\d+)$", r["review_id"])
    return (m.group(1), int(m.group(2))) if m else (r["review_id"], 0)

def clean(v):
    if isinstance(v, list):
        return "; ".join(str(x) for x in v)
    return str(v or "").replace("|", "／").replace("\n", " ")

def bib_escape(value):
    return str(value).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")

def build_bib(records):
    lines = [
        "% Generated by scripts/build_catalog.py.",
        "% Conference year and arXiv first-posting year are intentionally distinguished.",
        "",
    ]
    for r in records:
        entry_type = ("article" if r.get("entry_type") == "期刊论文" else
                      "inproceedings" if r.get("entry_type") in ("主会论文", "领域会议论文") else "misc")
        fields = [
            ("title", "{" + bib_escape(r["title"]) + "}"),
            ("author", " and ".join(bib_escape(a) for a in r["authors"])),
            ("year", r["year"]),
        ]
        if entry_type == "article":
            fields.append(("journal", bib_escape(r["venue"])))
        elif entry_type == "inproceedings":
            venue = re.sub(r"\s+(Poster|poster|Spotlight|spotlight|Oral|oral|Regular|regular)$", "", r["venue"])
            if "CoLLAs" in venue:
                venue = "Proceedings of the Third Conference on Lifelong Learning Agents"
            fields.append(("booktitle", bib_escape(venue)))
        else:
            fields.append(("howpublished", bib_escape(r["venue"])))
        for key in ("volume", "pages"):
            if r.get(key):
                value = str(r[key])
                if key == "pages":
                    value = re.sub(r"[-–]+", "--", value)
                fields.append((key, value))
        if r.get("doi"):
            fields.append(("doi", r["doi"]))
        fields.append(("url", r["url"]))
        arxiv = r.get("arxiv", "")
        if r.get("entry_type") == "预印本":
            arxiv = r["url"]
        if arxiv:
            fields += [("eprint", arxiv.rsplit("/", 1)[-1]), ("archivePrefix", "arXiv")]
        if "CoLLAs" in r.get("venue", ""):
            fields.append(("note", "CoLLAs 2024; proceedings published in 2025"))
        if entry_type == "misc":
            fields.append(("note", "Accessed 2026-09-22"))
        lines.append("@" + entry_type + "{plasticity" + r["review_id"] + ",\n" +
                     ",\n".join("  " + k + " = {" + str(v) + "}" for k, v in fields) +
                     "\n}\n")
    (ROOT / "references" / "plasticity.bib").write_text("\n".join(lines), encoding="utf-8")

def load():
    records = []
    for path in sorted(RECORDS.glob("*.json")):
        if path.name.startswith("_"):
            continue
        with path.open(encoding="utf-8") as f:
            records.append(json.load(f))
    records.sort(key=sort_key)
    ids = [r["review_id"] for r in records]
    titles = [r["title"].strip().lower() for r in records]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate review_id")
    if len(titles) != len(set(titles)):
        raise SystemExit("duplicate title")
    required = ("review_id", "title", "authors", "year", "venue", "url")
    for r in records:
        missing = [key for key in required if not r.get(key)]
        if missing:
            raise SystemExit(f"{r.get('review_id', '?')}: missing {', '.join(missing)}")
    return records

def build(records):
    (OUT / "records.json").write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    columns = [
        ("review_id", "编号"), ("priority", "优先级"), ("entry_type", "类型"),
        ("title", "标题"), ("authors", "作者"), ("year", "年份"),
        ("venue", "发表场所/来源"), ("status", "状态"), ("url", "原文链接"),
        ("doi", "DOI"), ("category", "主题"), ("key_findings", "核心发现"),
        ("tasks", "实验设置"), ("limitations", "阅读边界"), ("code_url", "代码"),
        ("accessed", "核验日期")]
    with (OUT / "catalog.csv").open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([label for _, label in columns])
        for r in records:
            row = []
            for key, _ in columns:
                value = r.get(key, "")
                if key == "authors":
                    value = "; ".join(value)
                if key == "code_url" and not value:
                    value = r.get("code", "")
                row.append(value or "")
            writer.writerow(row)
    def link(r):
        return f"[{r['title']}]({r['url']})"
    groups = [
        ("重点论文", [r for r in records if r.get("priority") == "重点"]),
        ("扩展论文", [r for r in records if r.get("priority") == "扩展"]),
        ("解读与代码", [r for r in records if r.get("priority") == "解读/代码"])]
    lines = ["# 文献目录", "",
             "> 本页由 python scripts/build_catalog.py 生成。", "",
             f"当前目录包含 **{len(records)}** 条记录：" +
             "、".join(f"{name} {len(rows)} 条" for name, rows in groups) + "。", ""]
    for name, rows in groups:
        lines += [f"## {name}", "", "| 编号 | 文献/资源 | 年份 | 来源 | 主题 |", "|---|---|---:|---|---|"]
        for r in rows:
            lines.append(f"| {r['review_id']} | {link(r)} | {r['year']} | {clean(r.get('venue'))} | {clean(r.get('category'))} |")
        lines.append("")
    (ROOT / "docs" / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    build_bib(records)

if __name__ == "__main__":
    records = load()
    build(records)
    print(f"built {len(records)} records")
