#!/usr/bin/env python3
"""Build aggregate catalog files from one JSON record per paper/resource."""
from pathlib import Path
import csv, json, re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = ROOT / "data" / "records"
OUT = ROOT / "data"

def sort_key(r):
    m = re.match(r"([A-Za-z]+)(\d+)$", r["review_id"])
    return (m.group(1), int(m.group(2))) if m else (r["review_id"], 0)

def clean(v):
    if isinstance(v, list):
        return "; ".join(str(x) for x in v)
    return str(v or "").replace("|", "／").replace("\n", " ")

def venue_en(value):
    return (str(value or "")
            .replace("（论文集发表于2025）", " (proceedings published in 2025)")
            .replace("伴随代码", " companion code"))

def paper_list_sections(records):
    sections = [
        ("Plasticity Loss and Recovery", [r for r in records if r.get("review_id", "").startswith("A")]),
        ("Neuroscience-Inspired Plasticity, Local Learning, and SNNs", [r for r in records if r.get("review_id", "").startswith("B")]),
        ("Language Models, Memory, and Adaptation", [r for r in records if r.get("review_id", "").startswith("C")]),
        ("Extended Papers", [r for r in records if r.get("review_id", "").startswith("E")]),
        ("Commentary and Code", [r for r in records if r.get("review_id", "").startswith(("RB", "RC"))]),
    ]
    lines = [
        "The lists below are generated from `data/records/*.json`.",
        "",
    ]
    for heading, rows in sections:
        if not rows:
            continue
        lines += [f"#### {heading}", "", "| ID | Paper or resource | Year | Venue / source |", "|---|---|---:|---|"]
        for r in rows:
            lines.append(f"| {r['review_id']} | [{r['title']}]({r['url']}) | {r['year']} | {venue_en(r.get('venue'))} |")
        lines.append("")
    return "\n".join(lines).rstrip()

def replace_generated_block(text, name, content):
    begin = f"<!-- BEGIN: GENERATED {name} -->"
    end = f"<!-- END: GENERATED {name} -->"
    if begin not in text or end not in text:
        raise SystemExit(f"README is missing generated block: {name}")
    before, remainder = text.split(begin, 1)
    _, after = remainder.split(end, 1)
    return before + begin + "\n\n" + content + "\n\n" + end + after

def bib_escape(value):
    return str(value).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")

def build_bib(records):
    lines = [
        "% Generated by scripts/build_catalog.py.",
        "% Conference year and arXiv first-posting year are intentionally distinguished.",
        "",
    ]
    for r in records:
        entry_type = ("article" if r.get("entry_type") == "期刊论文" else
                      "inproceedings" if r.get("entry_type") in ("主会论文", "领域会议论文") else "misc")
        fields = [
            ("title", "{" + bib_escape(r["title"]) + "}"),
            ("author", " and ".join(bib_escape(a) for a in r["authors"])),
            ("year", r["year"]),
        ]
        if entry_type == "article":
            fields.append(("journal", bib_escape(r["venue"])))
        elif entry_type == "inproceedings":
            venue = re.sub(r"\s+(Poster|poster|Spotlight|spotlight|Oral|oral|Regular|regular)$", "", r["venue"])
            if "CoLLAs" in venue:
                venue = "Proceedings of the Third Conference on Lifelong Learning Agents"
            fields.append(("booktitle", bib_escape(venue)))
        else:
            fields.append(("howpublished", bib_escape(r["venue"])))
        for key in ("volume", "pages"):
            if r.get(key):
                value = str(r[key])
                if key == "pages":
                    value = re.sub(r"[-–]+", "--", value)
                fields.append((key, value))
        if r.get("doi"):
            fields.append(("doi", r["doi"]))
        fields.append(("url", r["url"]))
        arxiv = r.get("arxiv", "")
        if r.get("entry_type") == "预印本":
            arxiv = r["url"]
        if arxiv:
            fields += [("eprint", arxiv.rsplit("/", 1)[-1]), ("archivePrefix", "arXiv")]
        if "CoLLAs" in r.get("venue", ""):
            fields.append(("note", "CoLLAs 2024; proceedings published in 2025"))
        if entry_type == "misc":
            fields.append(("note", "Accessed 2026-09-22"))
        lines.append("@" + entry_type + "{plasticity" + r["review_id"] + ",\n" +
                     ",\n".join("  " + k + " = {" + str(v) + "}" for k, v in fields) +
                     "\n}\n")
    (ROOT / "references" / "plasticity.bib").write_text("\n".join(lines), encoding="utf-8")

def load():
    records = []
    for path in sorted(RECORDS.glob("*.json")):
        if path.name.startswith("_"):
            continue
        with path.open(encoding="utf-8") as f:
            records.append(json.load(f))
    records.sort(key=sort_key)
    ids = [r["review_id"] for r in records]
    titles = [r["title"].strip().lower() for r in records]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate review_id")
    if len(titles) != len(set(titles)):
        raise SystemExit("duplicate title")
    required = ("review_id", "title", "authors", "year", "venue", "url")
    for r in records:
        missing = [key for key in required if not r.get(key)]
        if missing:
            raise SystemExit(f"{r.get('review_id', '?')}: missing {', '.join(missing)}")
    return records

def build(records):
    (OUT / "records.json").write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    columns = [
        ("review_id", "编号"), ("priority", "优先级"), ("entry_type", "类型"),
        ("title", "标题"), ("authors", "作者"), ("year", "年份"),
        ("venue", "发表场所/来源"), ("status", "状态"), ("url", "原文链接"),
        ("doi", "DOI"), ("category", "主题"), ("key_findings", "核心发现"),
        ("tasks", "实验设置"), ("limitations", "阅读边界"), ("code_url", "代码"),
        ("accessed", "核验日期")]
    with (OUT / "catalog.csv").open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([label for _, label in columns])
        for r in records:
            row = []
            for key, _ in columns:
                value = r.get(key, "")
                if key == "authors":
                    value = "; ".join(value)
                if key == "code_url" and not value:
                    value = r.get("code", "")
                row.append(value or "")
            writer.writerow(row)
    paper_lists = paper_list_sections(records)
    contents = "\n".join([
        f"- [Paper Lists](#paper-lists): {sum(r.get('entry_type') not in ('解读/播客', '代码') for r in records)} papers and {sum(r.get('entry_type') in ('解读/播客', '代码') for r in records)} related resources.",
        "- [Research notes](docs/review.md): concepts, comparisons, limitations, and a suggested reading order.",
        "- [Structured catalog](data/catalog.csv): filterable metadata for all records.",
        "- [BibTeX](references/plasticity.bib): generated citation entries.",
        "- [One-record-per-paper data](data/records/): editable source records.",
        "- [Maintenance guide](CONTRIBUTING.md): add, update, and remove entries.",
    ])
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    readme = replace_generated_block(readme, "CONTENTS", contents)
    readme = replace_generated_block(readme, "PAPER LISTS", paper_lists)
    (ROOT / "README.md").write_text(readme, encoding="utf-8")
    docs_lines = [
        "# Paper Lists", "",
        "> This page is generated by `python scripts/build_catalog.py`. The same lists are embedded in the repository README.", "",
        paper_lists,
    ]
    (ROOT / "docs" / "index.md").write_text("\n".join(docs_lines) + "\n", encoding="utf-8")
    build_bib(records)

if __name__ == "__main__":
    records = load()
    build(records)
    print(f"built {len(records)} records")
