#!/usr/bin/env python3
"""Build aggregate catalog files from one JSON record per paper/resource."""
from pathlib import Path
import csv, json, re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = ROOT / "data" / "records"
OUT = ROOT / "data"

def sort_key(r):
    m = re.match(r"([A-Za-z]+)(\d+)$", r["review_id"])
    return (m.group(1), int(m.group(2))) if m else (r["review_id"], 0)

def clean(v):
    if isinstance(v, list):
        return "; ".join(str(x) for x in v)
    return str(v or "").replace("|", "／").replace("\n", " ")

def venue_en(value):
    return (str(value or "")
            .replace("（论文集发表于2025）", " (proceedings published in 2025)")
            .replace("伴随代码", " companion code"))

MAJOR_ORDER = [
    "Continual Learning and Plasticity Loss",
    "Neuroscience-Inspired Plasticity",
    "Language Models, Memory, and Adaptation",
    "Reviews, Commentary, and Code",
]

MINOR_ORDER = {
    "Continual Learning and Plasticity Loss": [
        "Problem Definition and Diagnostics",
        "Resets, Regeneration, and Regularization",
        "Dynamics, Spectral Structure, and Theory",
    ],
    "Neuroscience-Inspired Plasticity": [
        "Hebbian, Predictive, and Synaptic Rules",
        "Local Learning, Credit Assignment, and SNNs",
    ],
    "Language Models, Memory, and Adaptation": [
        "Language-Model Plasticity and Post-Training",
        "Test-Time Learning and Long-Term Memory",
        "Functional Adaptation and Model Geometry",
    ],
    "Reviews, Commentary, and Code": [
        "Commentary and Podcasts",
        "Official Implementations",
    ],
}

def entry_type_en(value):
    return {
        "期刊论文": "Journal paper",
        "主会论文": "Conference paper",
        "领域会议论文": "Workshop / field-conference paper",
        "预印本": "Preprint",
        "解读/播客": "Commentary / podcast",
        "代码": "Code",
    }.get(value, str(value or ""))

def anchor(value):
    return re.sub(r"[^a-z0-9 -]", "", value.lower()).replace(" ", "-")

def paper_list_sections(records):
    groups = {}
    for r in records:
        groups.setdefault((r["major_category"], r["minor_category"]), []).append(r)
    lines = [
        "The lists below are generated from `data/records/*.json`.",
        "",
    ]
    for major in MAJOR_ORDER:
        major_rows = [r for r in records if r.get("major_category") == major]
        if not major_rows:
            continue
        lines += [f"#### {major}", "", f"{len(major_rows)} items", ""]
        for minor in MINOR_ORDER[major]:
            rows = groups.get((major, minor), [])
            if not rows:
                continue
            lines += [f"##### {minor}", "", "| Paper or resource | Type | Year | Venue / source |", "|---|---|---:|---|"]
            for r in rows:
                lines.append(f"| [{r['title']}]({r['url']}) | {entry_type_en(r.get('entry_type'))} | {r['year']} | {venue_en(r.get('venue'))} |")
            lines.append("")
    return "\n".join(lines).rstrip()

def contents_block(records):
    lines = [
        f"- [Paper Lists](#paper-lists): {sum(r.get('entry_type') not in ('解读/播客', '代码') for r in records)} papers and {sum(r.get('entry_type') in ('解读/播客', '代码') for r in records)} related resources.",
    ]
    for major in MAJOR_ORDER:
        major_rows = [r for r in records if r.get("major_category") == major]
        if not major_rows:
            continue
        lines.append(f"  - [{major}](#{anchor(major)}) ({len(major_rows)})")
        for minor in MINOR_ORDER[major]:
            count = sum(1 for r in records if r.get("major_category") == major and r.get("minor_category") == minor)
            if count:
                lines.append(f"    - [{minor}](#{anchor(minor)}) ({count})")
    lines += [
        "- [Research notes](docs/review.md): concepts, comparisons, limitations, and a suggested reading order.",
        "- [Structured catalog](data/catalog.csv): filterable metadata for all records.",
        "- [BibTeX](references/plasticity.bib): generated citation entries.",
        "- [One-record-per-paper data](data/records/): editable source records.",
        "- [Maintenance guide](CONTRIBUTING.md): add, update, and remove entries.",
    ]
    return "\n".join(lines)

def replace_generated_block(text, name, content):
    begin = f"<!-- BEGIN: GENERATED {name} -->"
    end = f"<!-- END: GENERATED {name} -->"
    if begin not in text or end not in text:
        raise SystemExit(f"README is missing generated block: {name}")
    before, remainder = text.split(begin, 1)
    _, after = remainder.split(end, 1)
    return before + begin + "\n\n" + content + "\n\n" + end + after

def bib_escape(value):
    return str(value).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")

def build_bib(records):
    lines = [
        "% Generated by scripts/build_catalog.py.",
        "% Conference year and arXiv first-posting year are intentionally distinguished.",
        "",
    ]
    for r in records:
        entry_type = ("article" if r.get("entry_type") == "期刊论文" else
                      "inproceedings" if r.get("entry_type") in ("主会论文", "领域会议论文") else "misc")
        fields = [
            ("title", "{" + bib_escape(r["title"]) + "}"),
            ("author", " and ".join(bib_escape(a) for a in r["authors"])),
            ("year", r["year"]),
        ]
        if entry_type == "article":
            fields.append(("journal", bib_escape(r["venue"])))
        elif entry_type == "inproceedings":
            venue = re.sub(r"\s+(Poster|poster|Spotlight|spotlight|Oral|oral|Regular|regular)$", "", r["venue"])
            if "CoLLAs" in venue:
                venue = "Proceedings of the Third Conference on Lifelong Learning Agents"
            fields.append(("booktitle", bib_escape(venue)))
        else:
            fields.append(("howpublished", bib_escape(r["venue"])))
        for key in ("volume", "pages"):
            if r.get(key):
                value = str(r[key])
                if key == "pages":
                    value = re.sub(r"[-–]+", "--", value)
                fields.append((key, value))
        if r.get("doi"):
            fields.append(("doi", r["doi"]))
        fields.append(("url", r["url"]))
        arxiv = r.get("arxiv", "")
        if r.get("entry_type") == "预印本":
            arxiv = r["url"]
        if arxiv:
            fields += [("eprint", arxiv.rsplit("/", 1)[-1]), ("archivePrefix", "arXiv")]
        if "CoLLAs" in r.get("venue", ""):
            fields.append(("note", "CoLLAs 2024; proceedings published in 2025"))
        if entry_type == "misc":
            fields.append(("note", "Accessed 2026-09-22"))
        lines.append("@" + entry_type + "{plasticity" + r["review_id"] + ",\n" +
                     ",\n".join("  " + k + " = {" + str(v) + "}" for k, v in fields) +
                     "\n}\n")
    (ROOT / "references" / "plasticity.bib").write_text("\n".join(lines), encoding="utf-8")

def load():
    records = []
    for path in sorted(RECORDS.glob("*.json")):
        if path.name.startswith("_"):
            continue
        with path.open(encoding="utf-8") as f:
            records.append(json.load(f))
    records.sort(key=sort_key)
    ids = [r["review_id"] for r in records]
    titles = [r["title"].strip().lower() for r in records]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate review_id")
    if len(titles) != len(set(titles)):
        raise SystemExit("duplicate title")
    required = ("review_id", "title", "authors", "year", "venue", "url", "major_category", "minor_category")
    for r in records:
        missing = [key for key in required if not r.get(key)]
        if missing:
            raise SystemExit(f"{r.get('review_id', '?')}: missing {', '.join(missing)}")
        if r["major_category"] not in MAJOR_ORDER:
            raise SystemExit(f"{r['review_id']}: unknown major_category {r['major_category']}")
        if r["minor_category"] not in MINOR_ORDER.get(r["major_category"], []):
            raise SystemExit(f"{r['review_id']}: unknown minor_category {r['minor_category']}")
    return records

def build(records):
    (OUT / "records.json").write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    columns = [
        ("review_id", "内部键"), ("major_category", "大类"), ("minor_category", "小类"),
        ("priority", "优先级"), ("entry_type", "类型"),
        ("title", "标题"), ("authors", "作者"), ("year", "年份"),
        ("venue", "发表场所/来源"), ("status", "状态"), ("url", "原文链接"),
        ("doi", "DOI"), ("category", "主题"), ("key_findings", "核心发现"),
        ("tasks", "实验设置"), ("limitations", "阅读边界"), ("code_url", "代码"),
        ("accessed", "核验日期")]
    with (OUT / "catalog.csv").open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f, lineterminator="\n")
        writer.writerow([label for _, label in columns])
        for r in records:
            row = []
            for key, _ in columns:
                value = r.get(key, "")
                if key == "authors":
                    value = "; ".join(value)
                if key == "code_url" and not value:
                    value = r.get("code", "")
                row.append(value or "")
            writer.writerow(row)
    paper_lists = paper_list_sections(records)
    contents = contents_block(records)
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    readme = replace_generated_block(readme, "CONTENTS", contents)
    readme = replace_generated_block(readme, "PAPER LISTS", paper_lists)
    (ROOT / "README.md").write_text(readme, encoding="utf-8")
    docs_lines = [
        "# Paper Lists", "",
        "> This page is generated by `python scripts/build_catalog.py`. The same lists are embedded in the repository README.", "",
        paper_lists,
    ]
    (ROOT / "docs" / "index.md").write_text("\n".join(docs_lines) + "\n", encoding="utf-8")
    build_bib(records)

if __name__ == "__main__":
    records = load()
    build(records)
    print(f"built {len(records)} records")
